# Generated by Django 6.0.4 on 2026-05-02 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='PieceDetachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pièce détachée',
                'verbose_name_plural': 'Pièces détachées',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='maintenance.facture')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.piecedetachee')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='pieces',
            field=models.ManyToManyField(blank=True, through='maintenance.LigneFacture', to='maintenance.piecedetachee'),
        ),
        migrations.CreateModel(
            name='TicketReparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modele_telephone', models.CharField(max_length=100)),
                ('probleme', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_diagnostic', 'En diagnostic'), ('en_reparation', 'En réparation'), ('attente_pieces', 'Attente de pièces'), ('repare', 'Réparé'), ('livre', 'Livré'), ('non_reparable', 'Non réparable')], default='recu', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de réparation',
                'verbose_name_plural': 'Tickets de réparation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='maintenance.ticketreparation'),
        ),
    ]
