# Generated by Django 6.0.4 on 2026-05-08 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='piecedetachee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticketreparation',
            options={},
        ),
        migrations.RemoveField(
            model_name='facture',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='ticketreparation',
            name='date_mise_a_jour',
        ),
        migrations.AlterField(
            model_name='facture',
            name='cout_main_oeuvre',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maintenance.ticketreparation'),
        ),
        migrations.AlterField(
            model_name='ticketreparation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketreparation',
            name='statut',
            field=models.CharField(choices=[('recu', 'Reçu'), ('reparation', 'En réparation'), ('pret', 'Prêt'), ('livre', 'Livré')], default='recu', max_length=30),
        ),
    ]
