# Generated by Django 6.0.4 on 2026-05-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_facture_options_alter_piecedetachee_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketreparation',
            old_name='probleme',
            new_name='probleme_declare',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='cout_main_oeuvre',
        ),
        migrations.RemoveField(
            model_name='ticketreparation',
            name='client',
        ),
        migrations.AddField(
            model_name='ticketreparation',
            name='client_nom',
            field=models.CharField(default='Client Passage', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketreparation',
            name='diagnostic_technique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketreparation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticketreparation',
            name='statut',
            field=models.CharField(choices=[('recu', 'Reçu (En attente)'), ('reparation', 'En cours de réparation'), ('pret', 'Réparé - Prêt pour retrait'), ('livre', 'Livré au client')], default='recu', max_length=30),
        ),
    ]
