# Generated by Django 6.0.4 on 2026-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_rename_probleme_ticketreparation_probleme_declare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreparation',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
